// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.LeptonTheme.Management;

// ReSharper disable once CheckNamespace
namespace Volo.Abp.LeptonTheme.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ILeptonThemeSettingsAppService), typeof(LeptonThemeSettingsClientProxy))]
public partial class LeptonThemeSettingsClientProxy : ClientProxyBase<ILeptonThemeSettingsAppService>, ILeptonThemeSettingsAppService
{
    public virtual async Task<LeptonThemeSettingsDto> GetAsync()
    {
        return await RequestAsync<LeptonThemeSettingsDto>(nameof(GetAsync));
    }

    public virtual async Task UpdateAsync(UpdateLeptonThemeSettingsDto input)
    {
        await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateLeptonThemeSettingsDto), input }
        });
    }
}
